### ISSUE TITLE
Delete failure when cluster has no certs

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#132]
If the cluster has no certificates loaded for some reason (i.e. the fields are NULL in the database), we should no-op that and move forward with the delete or otherwise we loop:

```
2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall [-] Fixed interval looping call 'magnum.service.periodic.ClusterUpdateJob.update_status' failed: ValueError: Container incorrectly specified.2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall Traceback (most recent call last):2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall   File "/var/lib/openstack/lib/python3.10/site-packages/barbicanclient/base.py", line 45, in validate_ref_and_return_uuid2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall     ref_pieces = ref.rstrip('/').rsplit('/', 1)2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall AttributeError: 'NoneType' object has no attribute 'rstrip'2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall 2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall During handling of the above exception, another exception occurred:2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall 2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall Traceback (most recent call last):2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_service/loopingcall.py", line 150, in _run_loop2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall     result = func(*self.args, **self.kw)2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall   File "/var/lib/openstack/lib/python3.10/site-packages/magnum/service/periodic.py", line 73, in update_status2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall     cdriver.update_cluster_status(self.ctx, self.cluster)2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/driver.py", line 119, in update_cluster_status2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall     resources.ApiCertificateAuthoritySecret(self.k8s_api, cluster).delete()2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/resources.py", line 115, in delete2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall     resource = self.get_object()2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/resources.py", line 388, in get_object2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall     ca_cert = cert_manager.get_backend().CertManager.get_cert(2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall   File "/var/lib/openstack/lib/python3.10/site-packages/magnum/common/cert_manager/barbican_cert_manager.py", line 174, in get_cert2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall     cert_container = connection.containers.register_consumer(2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall   File "/var/lib/openstack/lib/python3.10/site-packages/barbicanclient/v1/containers.py", line 745, in register_consumer2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall     container_uuid = base.validate_ref_and_return_uuid(2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall   File "/var/lib/openstack/lib/python3.10/site-packages/barbicanclient/base.py", line 48, in validate_ref_and_return_uuid2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall     raise ValueError('{0} incorrectly specified.'.format(entity))2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall ValueError: Container incorrectly specified.2023-06-22 17:53:40.052 1 ERROR oslo.service.loopingcall 
```

**Comment by runlevel-six** [comment]
Will this also clean-up clusters that were affected by the issue in the first place? For example, I have several clusters that are in "CREATED_FAILED" state because of this bug, and a few that were in that state that we tried to delete and have been stuck in "DELETE_IN_PROGRESS". If this won't fix it, could you could include steps to fix those clusters?

![image](https://github.com/vexxhost/magnum-cluster-api/assets/14925864/5204ba18-66b4-4022-8e18-2a64993413f9)
