### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'stdout'

### ISSUE THREAD

**Issue by mnaser** [vexxhost/magnum-cluster-api#143]
```
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_messaging/rpc/server.py", line 165, in _process_incoming
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_messaging/rpc/dispatcher.py", line 309, in dispatch
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_messaging/rpc/dispatcher.py", line 229, in _do_dispatch
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum/conductor/handlers/cluster_conductor.py", line 280, in cluster_resize
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server     cluster_driver.resize_cluster(context, cluster, resize_manager,
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/driver.py", line 211, in resize_cluster
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server     resources.apply_cluster_from_magnum_cluster(context, self.k8s_api, cluster)
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/resources.py", line 1839, in apply_cluster_from_magnum_cluster
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server     ClusterAutoscalerHelmRelease(api, cluster).apply()
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/helm.py", line 89, in __call__
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server     if "STATUS: pending" in str(status.stdout):
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server AttributeError: 'tuple' object has no attribute 'stdout'
openstack/magnum-conductor-0[magnum-conductor]: 2023-07-02 03:44:24.840 9 ERROR oslo_messaging.rpc.server
```

**Comment by mnaser** [comment]
attempted fix here https://github.com/vexxhost/magnum-cluster-api/commit/5b9bbcad90c9530cd76bdba850c0e455efe027bd
