### ISSUE TITLE
Scaling a cluster fails through command line

### ISSUE THREAD

**Issue by jessica-hofmeister** [vexxhost/magnum-cluster-api#155]
Attempting to scale up a magnum-created cluster from 2 to 3 nodes with the below command fails 
`openstack coe cluster update <cluster name> replace node_count=3`

However, using the Horizon GUI to scale up from 2 to 3 nodes works fine

below are the logs from the magnum conductor 

```log
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server [None req-63fc5d34-51aa-4b25-b88b-ed1f83d82532 - - - - - -] Exception during message handling: NotImplementedError
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_messaging/rpc/server.py", line 165, in _process_incoming
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_messaging/rpc/dispatcher.py", line 309, in dispatch
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/oslo_messaging/rpc/dispatcher.py", line 229, in _do_dispatch
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum/conductor/handlers/cluster_conductor.py", line 158, in cluster_update
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server     cluster_driver.update_cluster(context, cluster, manager, rollback)
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server   File "/var/lib/openstack/lib/python3.10/site-packages/magnum_cluster_api/driver.py", line 132, in update_cluster
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server     raise NotImplementedError()
2023-07-06 16:05:39.686 10 ERROR oslo_messaging.rpc.server NotImplementedError
```

**Comment by runlevel-six** [comment]
The logs from CAPI show no activity, so it looks like this solely fails on the magnum side.

**Comment by fnpanic** [comment]
It looks like horizon ui is not using the same function as you used on the CLI.

**Comment by mnaser** [comment]
> It looks like horizon ui is not using the same function as you used on the CLI.
> 
> openstack coe cluster resize --node_count=2 ….

Indeed, that's the way to go about it.  The `update` command is a bit.. useless in Magnum right now.

Thanks @fnpanic and hope this helps @jessica-hofmeister !
