### ISSUE TITLE
Non-existing resources should not stop cluster deletion

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/magnum-cluster-api#20]
```shell
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server [None req-8f39cccc-1fc0-4aab-9062-b9fea14ece2e None None] Exception during message handling: pykube.exceptions.ObjectDoesNotExist: k8s-v1.25.3-74wufkfiei-cloud-config does not exist.
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server Traceback (most recent call last):
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python3.8/dist-packages/oslo_messaging/rpc/server.py", line 165, in _process_incoming
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python3.8/dist-packages/oslo_messaging/rpc/dispatcher.py", line 309, in dispatch
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python3.8/dist-packages/oslo_messaging/rpc/dispatcher.py", line 229, in _do_dispatch
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/usr/local/lib/python3.8/dist-packages/osprofiler/profiler.py", line 159, in wrapper
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/opt/stack/magnum/magnum/conductor/handlers/cluster_conductor.py", line 191, in cluster_delete
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     cluster_driver.delete_cluster(context, cluster)
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/home/ubuntu/magnum-cluster-api/magnum_cluster_api/driver.py", line 194, in delete_cluster
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     resources.Cluster(context, self.k8s_api, cluster).delete()
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/home/ubuntu/magnum-cluster-api/magnum_cluster_api/resources.py", line 56, in delete
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     resource = self.get_object()
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/home/ubuntu/magnum-cluster-api/magnum_cluster_api/resources.py", line 1299, in get_object
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     utils.generate_cloud_controller_manager_config(
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/home/ubuntu/magnum-cluster-api/magnum_cluster_api/utils.py", line 56, in generate_cloud_controller_manager_config
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     data = pykube.Secret.objects(api, namespace="magnum-system").get_by_name(
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server   File "/home/ubuntu/.local/lib/python3.8/site-packages/pykube/query.py", line 116, in get_by_name
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server     raise ObjectDoesNotExist(f"{name} does not exist.")
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server pykube.exceptions.ObjectDoesNotExist: k8s-v1.25.3-74wufkfiei-cloud-config does not exist.
Nov 07 13:31:09 devstack magnum-conductor[2806024]: ERROR oslo_messaging.rpc.server 

```

**Comment by okozachenko1203** [comment]
this was fixed after reapply new CAPO manifests i think

**Comment by okozachenko1203** [comment]
This happens again.
## How to reproduce
If it fails before [apply_cluster_from_magnum_cluster](https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/driver.py#L59) to create cluster, `cloudControllerManagerConfig` is not created.
It results up `pykube.exceptions.ObjectDoesNotExist: k8s-v1.25.3-bcew4kh9xz-cloud-config does not exist` error and any actions like update/delete fails.

**Comment by mnaser** [comment]
maybe we can just use pykube API directly to delete the cluster object since we have the name.

something like:

```
capi_cluster = objects.Cluster.objects(api, namespace="magnum-system").get_or_none(utils.get_or_generate_cluster_name(self.cluster))
capi_cluster.delete()
```
