### ISSUE TITLE
Create cluster with error assert CONF.cluster_template.kubernetes_allowed_network_drivers

### ISSUE THREAD

**Issue by ngyenhuukhoi** [vexxhost/magnum-cluster-api#247]
Hello

I try to create new cluster with magnum cluster api but I encounter these error:
````

 [req-9239f0cf-67ac-45e3-a38a-f9fd3a914c32 - - - - -] Exception during message handling: AssertionError
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/rpc/server.py", line 165, in _process_incoming
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/rpc/dispatcher.py", line 309, in dispatch
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/oslo_messaging/rpc/dispatcher.py", line 229, in _do_dispatch
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/osprofiler/profiler.py", line 160, in wrapper
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server     result = f(*args, **kwargs)
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/magnum/conductor/handlers/cluster_conductor.py", line 78, in cluster_create
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server     cluster_driver.create_cluster(context, cluster, create_timeout)
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/magnum_cluster_api/driver.py", line 63, in create_cluster
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server     resources.apply_cluster_from_magnum_cluster(context, self.k8s_api, cluster)
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/magnum_cluster_api/resources.py", line 2030, in apply_cluster_from_magnum_cluster
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server     ClusterResourcesConfigMap(context, api, cluster).apply()
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/magnum_cluster_api/resources.py", line 101, in apply
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server     resource = self.get_object()
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python3.8/site-packages/magnum_cluster_api/resources.py", line 162, in get_object
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server     assert CONF.cluster_template.kubernetes_allowed_network_drivers == ["calico"]
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server AssertionError
2023-11-14 13:28:36.077 108 ERROR oslo_messaging.rpc.server 

````

My Openstack: yoga using kolla-ansilbe on Ubuntu 22.04
magnum-capi: v0.11.2 
Cluster-api: 1.5.3
k8s management cluster: 1.23.1
Image: ubuntu-2004-v1.25.3.qcow2

**Comment by ngyenhuukhoi** [comment]
When I debug I see CONF.cluster_template.kubernetes_allowed_network_drivers return value "all"/

**Comment by mnaser** [comment]
@ngyenhuukhoi since we only allow (and support) calico for now, we suggest setting `kubernetes_allowed_network_drivers` to `calico`

I think Flannel is broken in Magnum anyways.  Let me know if this fixes it.

**Comment by ngyenhuukhoi** [comment]
Hello. Thank you for your reply.
I just change in magnum configure and it worked like charm.

**Comment by ngyenhuukhoi** [comment]
I added in magnum.conf

[cluster_template]
kubernetes_allowed_network_drivers = calico
kubernetes_default_network_driver = calico
