### ISSUE TITLE
OVN as backend for octavia

### ISSUE THREAD

**Issue by mathgonzlez** [vexxhost/magnum-cluster-api#347]
Hi, 

Is the CAPI for openstack capable of use OVN backend as default for octavia? because i do a workaround for use ovn with as default lb and the initial deploy is succes:

`[DEFAULT]`

`[api_settings]`
`enabled_provider_drivers = ovn:OVN provider`
`default_provider_driver = ovn`

`[driver_agent]`
`enabled_provider_agents = ovn`

But every time the cluster need to create a new LB ip i receive this warning and nothing is created:

`2024-03-20 01:41:03.847 24 WARNING octavia.api.drivers.driver_factory [None req-c0011348-0b65-4d6a-b1ba-f4db8565fbaf - 01adb0aae1b94bd493311c94456643a4 - - default default] Requested provider driver 'amphora' was not enabled in the configuration file.****`

**Comment by mnaser** [comment]
@mathgonzlez so are you seeing this when the workload cluster (aka the one created by the driver) is attempting to create an Octavia load balancer for clusters that are `type` of `LoadBalancer`?

**Comment by mnaser** [comment]
@mathgonzlez the PR attached should do the trick, I'll wait for CI and then merge if it passes.

You'll need to provide the `octavia_provider` label to the cluster and set it to `ovn` for it to go through. :)

**Comment by mathgonzlez** [comment]
> @mathgonzlez so are you seeing this when the workload cluster (aka the one created by the driver) is attempting to create an Octavia load balancer for clusters that are `type` of `LoadBalancer`?

The issue is when i try to expose a service using LoadBalancer type, because the main loadbalancer is created and working. But when you try to expose one service the driver try to use 'Amphora' as backend

**Comment by mathgonzlez** [comment]
I add the label octavia_provider=ovn to cluster creation but i receive the same error. im in kolla-ansible but i added 'pip install magnum-cluster-api' to magnum_api as is described here:
https://github.com/vexxhost/magnum-cluster-api/issues/56

Maybe im missing something with the configuration?

**Comment by mathgonzalezz** [comment]
now i receive an error related with the algorithm used because ovn is not compatible. its mandatory to use rr?:

2024-04-05 21:04:49.759 22 INFO octavia.api.drivers.utils [None req-52d882c9-5817-4f83-bb50-65438b0135a7 - 01adb0aae1b94bd493311c94456643a4 - - default default] Provider 'ovn' raised an unsupported option error: OVN provider does not support ROUND_ROBIN algorithm
2024-04-05 21:04:49.764 22 ERROR wsme.api [None req-52d882c9-5817-4f83-bb50-65438b0135a7 - 01adb0aae1b94bd493311c94456643a4 - - default default] Server-side error: "Provider 'ovn' does not support a requested option: OVN provider does not support ROUND_ROBIN algorithm". Detail:
Traceback (most recent call last):

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/octavia/api/drivers/utils.py", line 52, in call_provider
    return driver_method(*args, **kwargs)

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/ovn_octavia_provider/driver.py", line 110, in loadbalancer_create
    self.pool_create(pool)

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/ovn_octavia_provider/driver.py", line 141, in pool_create
    self._check_for_supported_algorithms(pool.lb_algorithm)

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/ovn_octavia_provider/driver.py", line 67, in _check_for_supported_algorithms
    raise driver_exceptions.UnsupportedOptionError(

octavia_lib.api.drivers.exceptions.UnsupportedOptionError: OVN provider does not support ROUND_ROBIN algorithm


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/wsmeext/pecan.py", line 82, in callfunction
    result = f(self, *args, **kwargs)

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/octavia/api/v2/controllers/load_balancer.py", line 577, in post
    lock_session.rollback()

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/octavia/api/v2/controllers/load_balancer.py", line 567, in post
    driver_utils.call_provider(

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/octavia/api/drivers/utils.py", line 74, in call_provider
    raise exceptions.ProviderUnsupportedOptionError(

octavia.common.exceptions.ProviderUnsupportedOptionError: Provider 'ovn' does not support a requested option: OVN provider does not support ROUND_ROBIN algorithm
: octavia.common.exceptions.ProviderUnsupportedOptionError: Provider 'ovn' does not support a requested option: OVN provider does not support ROUND_ROBIN algorithm

**Comment by mnaser** [comment]
This would require another issue to allow modifying this indeed.

**Comment by mathgonzalezz** [comment]
Hi, i added #355

Thanks!
