### ISSUE TITLE
OVN octavia backend unsuported algorithm

### ISSUE THREAD

**Issue by mathgonzalezz** [vexxhost/magnum-cluster-api#355]
Hi, 

After the ovn implemetation i see some errors about a not supported algorithm that prevents to expose a service using octavia:

```
2024-04-05 21:04:49.759 22 INFO octavia.api.drivers.utils [None req-52d882c9-5817-4f83-bb50-65438b0135a7 - 01adb0aae1b94bd493311c94456643a4 - - default default] Provider 'ovn' raised an unsupported option error: OVN provider does not support ROUND_ROBIN algorithm
2024-04-05 21:04:49.764 22 ERROR wsme.api [None req-52d882c9-5817-4f83-bb50-65438b0135a7 - 01adb0aae1b94bd493311c94456643a4 - - default default] Server-side error: "Provider 'ovn' does not support a requested option: OVN provider does not support ROUND_ROBIN algorithm". Detail:
Traceback (most recent call last):

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/octavia/api/drivers/utils.py", line 52, in call_provider
    return driver_method(*args, **kwargs)

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/ovn_octavia_provider/driver.py", line 110, in loadbalancer_create
    self.pool_create(pool)

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/ovn_octavia_provider/driver.py", line 141, in pool_create
    self._check_for_supported_algorithms(pool.lb_algorithm)

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/ovn_octavia_provider/driver.py", line 67, in _check_for_supported_algorithms
    raise driver_exceptions.UnsupportedOptionError(

octavia_lib.api.drivers.exceptions.UnsupportedOptionError: OVN provider does not support ROUND_ROBIN algorithm


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/wsmeext/pecan.py", line 82, in callfunction
    result = f(self, *args, **kwargs)

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/octavia/api/v2/controllers/load_balancer.py", line 577, in post
    lock_session.rollback()

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/oslo_utils/excutils.py", line 227, in __exit__
    self.force_reraise()

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/oslo_utils/excutils.py", line 200, in force_reraise
    raise self.value

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/octavia/api/v2/controllers/load_balancer.py", line 567, in post
    driver_utils.call_provider(

  File "/var/lib/kolla/venv/lib64/python3.9/site-packages/octavia/api/drivers/utils.py", line 74, in call_provider
    raise exceptions.ProviderUnsupportedOptionError(

octavia.common.exceptions.ProviderUnsupportedOptionError: Provider 'ovn' does not support a requested option: OVN provider does not support ROUND_ROBIN algorithm
: octavia.common.exceptions.ProviderUnsupportedOptionError: Provider 'ovn' does not support a requested option: OVN provider does not support ROUND_ROBIN algorithm
```

This is the note for the ovn octavia backend doc:

Limitations of the OVN Provider Driver:
Only the SOURCE_IP_PORT load balancing algorithm is supported, others like ROUND_ROBIN and LEAST_CONNECTIONS are not currently supported.

Thanks!

**Comment by mnaser** [comment]
I pushed a PR for this, if you're able to test it, that would be really nice... since we use the Amphora provider for our CI, not OVN.

**Comment by mathgonzalezz** [comment]
> I pushed a PR for this, if you're able to test it, that would be really nice... since we use the Amphora provider for our CI, not OVN.

Hi!

Yes i can test it, i need only to update the python package right? because im using kolla ansible and magnun-api is containerized. But yes i go to test it and share results.

Thanks!

**Comment by mathgonzalezz** [comment]
i try to install but i dont find the 0.17 version:

```
ERROR: Could not find a version that satisfies the requirement magnum-cluster-api==0.17 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0)
ERROR: No matching distribution found for magnum-cluster-api==0.17
```

**Comment by mnaser** [comment]
@mathgonzalezz You will need to install directly from Git, 0.17.0 has not been released yet.

**Comment by mathgonzlez** [comment]
> @mathgonzalezz You will need to install directly from Git, 0.17.0 has not been released yet.

Sorry for this question, but are you able to help me installing? or you have some document that i can follow?

thanks!
