### ISSUE TITLE
MachineDeployment default-master not found

### ISSUE THREAD

**Issue by okozachenko1203** [vexxhost/magnum-cluster-api#414]
```sh
ERROR oslo.service.loopingcall Traceback (most recent call last):
ERROR oslo.service.loopingcall   File "/opt/stack/data/venv/lib/python3.10/site-packages/oslo_service/loopingcall.py", line 150, in _run_loop
ERROR oslo.service.loopingcall     result = func(*self.args, **self.kw)
ERROR oslo.service.loopingcall   File "/opt/stack/magnum/magnum/service/periodic.py", line 75, in update_status
ERROR oslo.service.loopingcall     cdriver.update_cluster_status(self.ctx, self.cluster)
ERROR oslo.service.loopingcall   File "/home/ubuntu/magnum-cluster-api/magnum_cluster_api/driver.py", line 39, in wrapper
ERROR oslo.service.loopingcall     return func(*args, **kwargs)
ERROR oslo.service.loopingcall   File "/home/ubuntu/magnum-cluster-api/magnum_cluster_api/driver.py", line 167, in update_cluster_status
ERROR oslo.service.loopingcall     ] + self.update_nodegroups_status(context, cluster)
ERROR oslo.service.loopingcall   File "/home/ubuntu/magnum-cluster-api/magnum_cluster_api/driver.py", line 475, in update_nodegroups_status
ERROR oslo.service.loopingcall     md_spec = cluster_resource.get_machine_deployment_spec(node_group.name)
ERROR oslo.service.loopingcall   File "/home/ubuntu/magnum-cluster-api/magnum_cluster_api/objects.py", line 274, in get_machine_deployment_spec
ERROR oslo.service.loopingcall     self.get_machine_deployment_index(name)
ERROR oslo.service.loopingcall   File "/home/ubuntu/magnum-cluster-api/magnum_cluster_api/objects.py", line 269, in get_machine_deployment_index
ERROR oslo.service.loopingcall     raise exceptions.MachineDeploymentNotFound(name=name)
ERROR oslo.service.loopingcall magnum_cluster_api.exceptions.MachineDeploymentNotFound: MachineDeployment default-master not found.
ERROR oslo.service.loopingcall 
```

**Comment by okozachenko1203** [comment]
https://github.com/vexxhost/magnum-cluster-api/pull/415
